// Processing 3.0a10

// assignment4v4.pde
// global variable declarations, importing needed java library,
// and basic structure of processing program which has setup and draw procedures 

import javax.swing.JOptionPane;
import java.awt.FileDialog;

/////////////////////////////////////////////////
// CANVAS & ...
/////////////////////////////////////////////////
PGraphics pg;
int x01, x02, y01, y02;
//int lineSize = 1;
color selectedColor = color(0);
boolean ribbonOn = true,
        isDoneSaving = false;
String tool = "line";
LineList lines = new LineList();
LineList clippedLines = new LineList();

/////////////////////////////////////////////////
// POLYGON
/////////////////////////////////////////////////
int np = 0;  // Number of points in the polygon;
Point[] polygon = new Point[50];  // !!!!!!! NEED VALIDATION FOR MORE THAN 50 POINTS
int tmpNp = 0;
Point tmpPoint = null;
Point[] tmpPolygon = new Point[50];
boolean drawnByDragged = false;  // Is a point of polygon generated by dragged mouse
boolean polygonFinished = true;  // Initially no drawing polygon in progress, so it is true

/////////////////////////////////////////////////
// STYLE
/////////////////////////////////////////////////
PImage img;  // for icon in the application
PFont font;  // for text in the application

// run first, only once
void setup() {
  frame.setTitle( "PCyrusBeck : Cyrus-Beck Clipping" );
  size( 800, 500 );
  smooth();
  
  // Font used in the application
  font = loadFont( "Calibri-Light-13.vlw" );
  textFont( font );  
  
  // create application icon
  img = loadImage( "sinter.png" );
  PGraphics icon = createGraphics(256, 256, JAVA2D);
  icon.beginDraw();
  icon.image(img, 0, 0, 256, 256);
  icon.endDraw();
  frame.setIconImage(icon.image);
  
  // create canvas
  pg = createGraphics( 800, 410 );
  pg.beginDraw();
    
  restoreDrawing( false );  // call the default canvas
}

// infinite loop
void draw() {
  pg.endDraw();        // keep end drawing in canvas to respond to the new drawing drawn by user
  image( pg, 0, 71 );  // keep generating drawing in canvas
  pg.beginDraw();
 
  statusBar();  // always show the status bar
  showRibbon(); // always show the ribbon
}
